### ISSUE TITLE
Tradução do plugin The Events Calendar

### ISSUE THREAD

**Issue by cpswsg** [womozbrasil/womoz.mozillabrasil.org.br#6]
Finalizar a tradução do plugin [The Events Calendar](https://wordpress.org/plugins/the-events-calendar/)

![bug-plugins-001](https://cloud.githubusercontent.com/assets/1923666/11309937/f653c8fa-8fad-11e5-97f4-ea917e0a9e12.png)
![bug-plugins-002](https://cloud.githubusercontent.com/assets/1923666/11309938/f93b9660-8fad-11e5-850e-d352e3ad26c3.png)

**Comment by halcance** [comment]
Plugin traduzido.
